name: robot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  convex_bottom_bar: ^2.5.1
  rxdart: ^0.27.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.12+4 
  fl_chart: ^0.12.0
  fluttertoast: ^3.1.0
  http: ^0.12.1
  percent_indicator: "^2.1.7+2"
  qr_flutter: ^3.1.0
  flutter_animation_progress_bar: ^1.0.6
  url_launcher: 
  clipboard: 
  syncfusion_flutter_gauges: ^18.2.44
  image_picker: ^0.6.7+22
  skeleton_text: ^1.0.0
  video_player: ^1.0.1
  awesome_dialog: ^1.3.2
  flutter_launcher_icons: 
  list_treeview: ^0.2.5+1
  package_info: 
  flutter_hms_gms_availability: ^1.0.0
  firebase_messaging: ^7.0.3
  flutter_spinkit: "^4.1.2"
  carousel_slider: ^4.0.0
  flutter_local_notifications:
  rxdart: ^0.27.1

flutter:
  uses-material-design: true

  assets:
    - lib/system/language/zh.json
    - lib/system/language/en.json
    - lib/system/language/id.json
    - lib/system/language/ms.json
    - lib/system/language/th.json
    - lib/assets/img/
    - lib/assets/img/serviceDetails/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/icon.png"